### ISSUE TITLE
400 The redirect_uri parameter must be a valid URI 

### ISSUE THREAD

**Issue by cc0der** [Diablo-Profile/diabloprofile-public#1]
### What are you trying to achieve?

Login with Battle.Net on [https://www.diabloprofile.com/login]()

### What is happening instead?

Battle.Net presents '400' error page with the text: The redirect_uri parameter must be a valid URI.
The URL is: [https://oauth.battle.net/oauth/authorize?client_id=77980e7c27734d4d8289c54e9ab36471&redirect_uri=0&scope&response_type=code&state=Qegqc6RS0E5qG3KArBAQnkpEclQdIJSA2IG7g5Sl]()
I suspect the `&redirect_uri=0` is wrong?

### Any additional info?

I am logged in to Battle.Net with the same browser (Firefox 99 on Windows 11)
My BattleTag is `ccoder#2263`

**Comment by Zemill** [comment]
Thank you for the notification.  Looks like a config was set wrong.  I have fixed that.  Can you try again and let me know if it resolves the issue for you

**Comment by cc0der** [comment]
It's working now, thanks!
